#!/bin/bash

# How many lines in sstatus output?
# Honor user environment setting if one exists
if [ -z ${Q_LINES+x} ] ; then
	Q_LINES=30
fi

set -u # Do not let us use undeclared variables

if [ $# -lt 1 ] ; then
	echo -e "\nI need the name of a service\n"
	echo -e "(e.g. $(basename $0) nginx)\n"
	exit 1
fi

Q_SERVICE=$1

sstatus()
{
	systemctl --lines $Q_LINES --no-pager status $Q_SERVICE
}

# What are we doing?
case $(basename $0) in

	sstart)
		sudo systemctl start $Q_SERVICE
		sstatus
		;;

	sstop)
		sudo systemctl stop $Q_SERVICE
		sstatus
		;;

	sstatus)
		sstatus
		;;

	senable)
		sudo systemctl enable $Q_SERVICE
		;;

	sdisable)
		sudo systemctl disable $Q_SERVICE
		;;

	quicksystemctl)
		echo -e "\nThe $(basename $0) script is not intended to be used directly\n"
		;;

	*)
		echo -e "\nUnknown option $(basename $0)\n"
		;;

esac


